config/routes.rb
StripeExample::Application.routes.draw do
  resources :payments

  devise_for :users
  

  root :to => 'payments#index'

end

app/models/payment.rb
# -*- coding: utf-8 -*-
class Payment < ActiveRecord::Base
  belongs_to :user
  attr_accessible :user, :amount, :stripe_token
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/payments_controller.rb
# -*- coding: utf-8 -*-
class PaymentsController < ApplicationController
  # GET /payments
  # GET /payments.json
  def index
    @payments = Payment.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @payments }
    end
  end

  # GET /payments/1
  # GET /payments/1.json
  def show
    @payment = Payment.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @payment }
    end
  end

  # GET /payments/new
  # GET /payments/new.json
  def new
    @payment = Payment.new

    if current_user and current_user.stripe_customer_token
      customer = Stripe::Customer.retrieve(current_user.stripe_customer_token)
      @cc_last_4 = customer.active_card.last4
    end

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @payment }
    end
  end

  # GET /payments/1/edit
  def edit
    @payment = Payment.find(params[:id])
  end

  # POST /payments
  # POST /payments.json
  def create
    amount = params[:payment][:amount].to_f
    
    params[:payment][:user] = nil if params[:payment][:user] == ""

    charge_info = {
      amount:      (amount * 100).to_i,
      description: 'Stripe Example Charge',
      currency:    'usd'
    }

    begin
      if current_user
        if current_user.stripe_customer_token
          customer = Stripe::Customer.retrieve(current_user.stripe_customer_token)
          
          if params[:saved_card] == 'false'
            customer.card = params[:payment][:stripe_token]
            customer.save
          end
        else
          customer = Stripe::Customer.create(
            :email => current_user.email,
            :card  => params[:payment][:stripe_token]
          )
          current_user.update_attribute(:stripe_customer_token, customer.id)
        end
        
        charge = Stripe::Charge.create( charge_info.merge({ customer: customer.id }) )
        
        params[:payment][:user] = current_user
      else
        charge = Stripe::Charge.create( charge_info.merge({ card: params[:payment][:stripe_token] }) )
      end

      params[:payment][:stripe_token] = charge.id
      @payment = Payment.new(params[:payment])
      
      respond_to do |format|
        if @payment.save
          format.html { redirect_to @payment, notice: 'Payment was successfully created.' }
          format.json { render json: @payment, status: :created, location: @payment }
        else
          format.html { render action: "new" }
          format.json { render json: @payment.errors, status: :unprocessable_entity }
        end
      end
    rescue Stripe::InvalidRequestError => e
      redirect_to new_payment_path, notice: e.message
    end
  end

  # PUT /payments/1
  # PUT /payments/1.json
  def update
    @payment = Payment.find(params[:id])

    respond_to do |format|
      if @payment.update_attributes(params[:payment])
        format.html { redirect_to @payment, notice: 'Payment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @payment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /payments/1
  # DELETE /payments/1.json
  def destroy
    @payment = Payment.find(params[:id])
    @payment.destroy

    respond_to do |format|
      format.html { redirect_to payments_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Stripe Example</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= javascript_include_tag "https://js.stripe.com/v1/" %>
  <%= javascript_include_tag "http://stripe.github.io/jquery.payment/lib/jquery.payment.js" %>
  <%= javascript_tag "Stripe.publishableKey = '#{Rails.configuration.stripe[:publishable_key]}';" %>
  <%= csrf_meta_tags %>
</head>
<body>
 <p class="notice"><%= notice %></p>
 <p class="alert"><%= alert %></p>

<a href="https://github.com/wholcomb/stripe_example"><img style="position: absolute; top: 0; right: 0; border: 0;" src="https://s3.amazonaws.com/github/ribbons/forkme_right_red_aa0000.png" alt="Fork me on GitHub"/></a>

<%= yield %>

<script type="text/javascript">
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-42087393-2', 'herokuapp.com');
  ga('send', 'pageview');
</script>
</body>
</html>

app/views/payments/_form.html.erb
<%= form_for(@payment) do |f| %>
  <% if @payment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@payment.errors.count, "error") %> prohibited this payment from being saved:</h2>

      <ul>
      <% @payment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%- if @cc_last_4 %>
    <div class="field">
      <input type="radio" name="saved_card" value="true"/> Saved Card
      <input type="radio" name="saved_card" value="false"/> New Card
    </div>

    <div id="saved_card">
      <div class="field">
        <label>Saved Card</label>
        <input id="saved-number" type="text" disabled="true" value="&bull;&bull;&bull;&bull; &bull;&bull;&bull;&bull; &bull;&bull;&bull;&bull; <%= @cc_last_4 %>" />
      </div>
    </div>
  <%- end %>
  <div id="new_card">
    <div class="field">
      <%= f.hidden_field :stripe_token %>
    </div>
    <div class="field">
      <label>Card Number</label>
      <input id="card-number" type="text" placeholder="4242 4242 4242 4242" />
    </div>
    <div class="field">
      <label>CV Code</label>
      <input id="cvc" type="text" placeholder="123" />
    </div>
    <div class="field">
      <label>Expiry Month</label>
      <input id="exp-month" type="text" placeholder="12" />
    </div>
    <div class="field">
      <label>Expiry Year</label>
      <input id="exp-year" type="text" placeholder="14" />
    </div>
  </div>
  <div class="field">
    <%= f.label :amount %><br />
    <%= f.text_field :amount %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/payments/edit.html.erb
<h1>Editing payment</h1>

<%= render 'form' %>

<%= link_to 'Show', @payment %> |
<%= link_to 'Back', payments_path %>

app/views/payments/index.html.erb
<%- if current_user %>
  <p>Logged in as: <%= current_user.email %>
  <%= link_to('Logout', main_app.destroy_user_session_path, :method => :delete) %>
<%- else %>
  <%= link_to('Login', main_app.new_user_session_path) unless current_user %>
<%- end %>


<h1>Listing payments</h1>

<table>
  <tr>
    <th>Stripe token</th>
    <th>Amount</th>
    <th>User</th>
    <th>Date</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @payments.each do |payment| %>
  <tr>
    <td><%= payment.stripe_token %></td>
    <td><%= number_to_currency payment.amount %></td>
    <td><%= payment.user.email if payment.user %></td>
    <td><%= payment.created_at %></td>
    <td><%= link_to 'Show', payment %></td>
    <td><%= link_to 'Edit', edit_payment_path(payment) %></td>
    <td><%= link_to 'Destroy', payment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Payment', new_payment_path %>

app/views/payments/new.html.erb
<h1>New payment</h1>

<div id="credit-card-errors">
  <p id="stripe-error-message"/>
</div>

<p><a href="https://stripe.com/docs/testing#cards">Test card numbers</a></p>

<%= render 'form' %>

<%= link_to 'Back', payments_path %>

app/views/payments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Stripe token:</b>
  <%= @payment.stripe_token %>
</p>

<p>
  <b>Amount:</b>
  <%= @payment.amount %>
</p>

<p>
  <b>User:</b>
  <%= @payment.user.email if @payment.user %>
</p>


<%= link_to 'Edit', edit_payment_path(@payment) %> |
<%= link_to 'Back', payments_path %>